version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  backend:
    build: .
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - kafka
      - redis
